
name: Run CTI Automator

on:
  workflow_dispatch:

jobs:
  fetch-threats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          ls -la
          pip install requests

      - name: Run script
        run: |
          cd $GITHUB_WORKSPACE
          python fetch_threats.py

      - name: Commit threat data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add threats.csv
          git diff --staged --quiet || git commit -m "Updated threat feed $(date)"
          git push
